name: CI (on branch push)
on:
  push:
    branches:

jobs:
  install:
    runs-on: ubuntu-latest
    name: Maven Install
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - run: mvn -B install
