name: Maven POM CI
on: [ push ]
jobs:
  validate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
        java: [ 11, 17, 19 ]
        distribution: 'temurin'
      fail-fast: false
      max-parallel: 4
    name: Maven POM validation for OS ${{ matrix.os }} and JDK ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
          cache: maven
      - name: Validate Maven POM
        run: ./mvnw validate -B
