name: Release to Maven Central
on:
  release:
    types: [ created ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: [ ubuntu-latest ]
    name: POM deployment to Maven Central
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          cache: maven
      - run: mvn -B -Prelease deploy
